### PR TITLE
documentation now built and hosted by readthedocs

### PR DESCRIPTION
**Pull request by tristan0x**
This contribution provides the integration of readthedocs to continuously build and host the package documentation.

- CI: add readthedocs rc file so that they can build MultiscaleRun documentation themselve
- CI: remove build and release of the documentation on BBP GitLab
- cleanup documentation extra dependencies
- update links to the documentation

### CODE REVIEW

**Comment by cattabiani** [comment]
I think you need to change the readme too. I added a link to the old bbp docs back in the days as people were coming asking me for the link

**Comment by cattabiani** [comment]
where are the docs exactly? I wanted to learn how this process works but I cannot find anything in https://multiscalerun.rtfd.io/

**Comment by tristan0x** [comment]
> where are the docs exactly? I wanted to learn how this process works but I cannot find anything in https://multiscalerun.rtfd.io/

It will be deployed at this location once this PR is merged.

In the meantime, you can look at the documentation build of this PR by clicking on the link highlighted in the image
image

**Comment by tristan0x** [comment]
Here is [some documentation](https://docs.readthedocs.io/en/stable/integrations.html) on how the GitHub integration works

**Comment by tristan0x** [comment]
Do you need more information to approve the PR or can we move forward @cattabiani ?

**Comment by cattabiani** [comment]
ah! I did not notice that link. I will approve soon

**Review by cattabiani — APPROVED** [review]
LGTM

**Pull request merged**
